name: flutter_todo_app
description: A Flutter sample app demonstrating notion_dart_kit usage for task management.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Notion API client
  notion_dart_kit:
    path: ../../

  # State management
  flutter_riverpod: ^2.5.1

  # Environment variables
  flutter_dotenv: ^5.1.0

  # UI utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
