name: notion_dart_kit
description: A comprehensive, type-safe Dart toolkit for the Notion API. Full endpoint coverage, built-in rate limiting, retry logic, and intuitive query DSL for Dart & Flutter.
version: 0.1.0
homepage: https://github.com/Haruki1090/notion-dart-kit
repository: https://github.com/Haruki1090/notion-dart-kit
issue_tracker: https://github.com/Haruki1090/notion-dart-kit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0               # HTTPクライアント
  json_annotation: ^4.8.1   # JSONシリアライズ用アノテーション
  freezed_annotation: ^3.1.0 # Immutableクラス生成用
  meta: ^1.10.0             # メタデータアノテーション

dev_dependencies:
  build_runner: ^2.4.6      # コード生成ツール
  freezed: ^3.2.3           # Freezedコードジェネレータ
  json_serializable: ^6.7.1 # JSONシリアライズコード生成
  test: ^1.24.0             # テストフレームワーク
  mockito: ^5.4.2           # モック生成
  lints: ^3.0.0             # Dartリンター