name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        default: 'v0.2.0'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: dart test --reporter expanded

      - name: Get tag name
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Check if release notes exist
        id: check_notes
        run: |
          if [ -f "RELEASE_NOTES_${{ steps.tag.outputs.tag }}.md" ]; then
            echo "notes_exist=true" >> $GITHUB_OUTPUT
            echo "notes_file=RELEASE_NOTES_${{ steps.tag.outputs.tag }}.md" >> $GITHUB_OUTPUT
          else
            echo "notes_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          RELEASE_NAME="Notion Dart Kit ${TAG}"
          
          # Create release body
          if [ "${{ steps.check_notes.outputs.notes_exist }}" = "true" ]; then
            BODY_FILE="${{ steps.check_notes.outputs.notes_file }}"
            gh release create "${TAG}" \
              --title "${RELEASE_NAME}" \
              --notes-file "${BODY_FILE}" \
              --verify-tag
          else
            cat > release_notes.md << EOF
          Release ${TAG} of Notion Dart Kit

          ## What's Changed

          See [CHANGELOG.md](https://github.com/Haruki1090/notion-dart-kit/blob/main/CHANGELOG.md) for detailed changes.

          ## Installation

          \`\`\`yaml
          dependencies:
            notion_dart_kit: ^${TAG}
          \`\`\`

          ## Documentation

          - [README](https://github.com/Haruki1090/notion-dart-kit/blob/main/README.md)
          - [API Documentation](https://pub.dev/documentation/notion_dart_kit/latest/)
          - [Examples](https://github.com/Haruki1090/notion-dart-kit/tree/main/example)
          EOF
            
            gh release create "${TAG}" \
              --title "${RELEASE_NAME}" \
              --notes-file release_notes.md \
              --verify-tag
          fi

  publish-to-pub:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Verify pub package
        run: dart pub publish --dry-run

      - name: Publish package
        run: dart pub publish --force
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}